### ISSUE TITLE
3.2.3 Search for Graphclass

### ISSUE THREAD

**Issue by Gong-Bao-Chicken** [SPSS13/SPSS13#23]
-  Das System soll die Möglichkeit bieten im gezeichneten Graphen eine Graphklasse zu suchen.

**Comment by byebb** [comment]
In der Liste werden auch Äquivalente Klassen von dem angezeigten Graphklassen angezeigt, da aber im gezeichneten Graphen nur ein Name (Label) angezeigt wird, muss der Name von dem Knoten bzgl, dem Namen, der bei Search in Drawing ausgewählt wird entsprechend angepasst werden. Ist das Label schon korrekt, muss nichts geändert werden.
