### ISSUE TITLE
3.2.10 System shall have Hyper-Link to "small graphs"

### ISSUE THREAD

**Issue by Gong-Bao-Chicken** [SPSS13/SPSS13#36]
Das System soll einen Hyper-Link zu "small graphs" besitzen.

**Comment by Gong-Bao-Chicken** [comment]
funktioniert nicht. also der link^^

**Comment by byebb** [comment]
Du hast nicht gerade die neuste Version oder?
Am 01.07.2013 19:34 schrieb "Philipp Hilpert" notifications@github.com:

**Comment by Gong-Bao-Chicken** [comment]
ich denke so ziemlich ... (?) :)

TopNavBar -> Help -> SmallGraphs 
- nichts passiert :S

**Comment by Gong-Bao-Chicken** [comment]
:dancer:
