### ISSUE TITLE
3.2.16 Zoom in and Out 

### ISSUE THREAD

**Issue by Gong-Bao-Chicken** [SPSS13/SPSS13#44]
Das System soll die Möglichkeit bieten, im erzeugten Graphen zu zoomen.

**Comment by Gong-Bao-Chicken** [comment]
geht - zwar noch buggy, aber geht.

**Comment by byebb** [comment]
funktioniert jetzt.. analog zu centerCanvas, wenn man über die Zoomstufen soweit geht, dass der Graph bereits kleiner als das sichtfenster wird, dann wird nach links oben gezoomt, ist aber ein akzeptabler kompromiss.. ich zeig euch das mal bei nem Treffen..
