### ISSUE TITLE
4.2 Zoom (Mausrad)

### ISSUE THREAD

**Issue by Gong-Bao-Chicken** [SPSS13/SPSS13#48]
Durch das Scrollen mit dem Mausrad wird das Bild gezoomt, Mausrad nach oben entspricht hinein zoomen, Mausrad nach unten entspricht heraus zoomen.

**Comment by FabianVollmer** [comment]
die positionierung funktioniert noch nicht einwandfrei, der zoom an sich schon

**Comment by Gong-Bao-Chicken** [comment]
noch ein wenig buggy?

**Comment by FabianVollmer** [comment]
zoom von matze integriert
denke der muss erstmal nicht weiter bearbeitet werden für die beta
