### ISSUE TITLE
4.9-4.18 Kontextmenü Show information

### ISSUE THREAD

**Issue by Gong-Bao-Chicken** [SPSS13/SPSS13#56]
- [x] 9. Man kann Knoten mit der rechten Maustaste anklicken um ein Kontextmenü zu öffnen.
- [ ] 10. Beinhaltet die bereits vorhandene Funktionalität.
- [ ] 11. Show Details blendet die Sidebar ein. (vgl. Sidebar Punkt 21)
- [ ] 12. Beinhaltet die bereits vorhandene Funktionalität (Change Name)
- [ ] 13. Kontextmenü-item um vom jeweiligen Knoten alle Nachbarknoten einzublenden.
- [ ] 14. Kontextmenü-item um vom jeweiligen Knoten alle Nachbarknoten auszublenden.
- [ ] 15. Kontextmenü-item um vom jeweiligen Knoten alle Superklassen einzublenden.
- [ ] 16. Kontextmenü-item um vom jeweiligen Knoten alle Superkklassen auszublenden.
- [ ] 17. Kontextmenü-item um vom jeweiligen Knoten alle Subklassen einzublenden.
- [ ] 18. Kontextmenü-item um vom jeweiligen Knoten alle Subklassen auszublenden.

**Comment by Gong-Bao-Chicken** [comment]
Change Name Funktioniert nicht richtig. 

Graph Classes:

Select (0,2)-colorable n chordal
- subclasses

Select caterpillar -> no name change possible, im ISGCI aber schon. :P

**Comment by FabianVollmer** [comment]
bug fixed
zeigt jetzt zwar auch den aktuellen namen an aber das sollte für die beta so reichen
