### ISSUE TITLE
mouse vanishes, when it should change form

### ISSUE THREAD

**Issue by 85pando** [SPSS13/SPSS13#78]
kwt

**Comment by Gong-Bao-Chicken** [comment]
Welche Version unter welchem Betriebssystem benutzen Sie? 

Viele Grüße, 
Ihr GraphMaga Support-Team

**Comment by 85pando** [comment]
dev-branch, MacOSX 10.? (Das was halt in der Fachschaft läuft)

**Comment by 85pando** [comment]
Fehler tritt nur auf, wenn man das jar direkt startet (-;
